### ISSUE TITLE
message signing does not work

### ISSUE THREAD

**Issue by jellegerbrandy** [burner-wallet/burner-connect-hub#1]
Message signing does not work, I get this error (which seems like a typo) when trying to sign a message 
Error: singMsg() not implemented Signer.js:34:10
​
reproduce this by:
- going to https://alchemy-competition-xdai.herokuapp.com/ 
- login, connect to burnet wallet
- try to follow something (or create a profile)
--------------------------

**Comment by dmihal** [comment]
@jellegerbrandy We're using contract wallets, so direct signatures won't be possible.

Does alchemy support ERC-1271?

**Comment by jellegerbrandy** [comment]
We are using 3box (for profile info and saving personal info).  Need to check for support there (and how to handle that)

**Comment by dmihal** [comment]
Fixed in @burner-factory/contract-wallet-signer@0.2.2, which will be included in future wallet deployments
